#############################################################################
# Makefile for building: udptcp
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  udptcp.pro
# Template: app
# Command: /home/joaovfabri/miniconda2/bin/qmake -o Makefile udptcp.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../miniconda2/include/qt -I../miniconda2/include/qt/QtWidgets -I../miniconda2/include/qt/QtGui -I../miniconda2/include/qt/QtNetwork -I../miniconda2/include/qt/QtCore -I. -I. -I../miniconda2/mkspecs/linux-g++
QMAKE         = /home/joaovfabri/miniconda2/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/joaovfabri/miniconda2/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/joaovfabri/miniconda2/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = udptcp1.0.0
DISTDIR = /home/joaovfabri/udptcp/.tmp/udptcp1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/joaovfabri/miniconda2/lib
LIBS          = $(SUBLIBS) -L/home/joaovfabri/miniconda2/lib -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		server.cpp \
		client.cpp moc_mainwindow.cpp \
		moc_server.cpp \
		moc_client.cpp
OBJECTS       = main.o \
		mainwindow.o \
		server.o \
		client.o \
		moc_mainwindow.o \
		moc_server.o \
		moc_client.o
DIST          = ../miniconda2/mkspecs/features/spec_pre.prf \
		../miniconda2/mkspecs/common/unix.conf \
		../miniconda2/mkspecs/common/linux.conf \
		../miniconda2/mkspecs/common/sanitize.conf \
		../miniconda2/mkspecs/common/gcc-base.conf \
		../miniconda2/mkspecs/common/gcc-base-unix.conf \
		../miniconda2/mkspecs/common/g++-base.conf \
		../miniconda2/mkspecs/common/g++-unix.conf \
		../miniconda2/mkspecs/qconfig.pri \
		../miniconda2/mkspecs/modules/qt_lib_3danimation.pri \
		../miniconda2/mkspecs/modules/qt_lib_3danimation_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dcore.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dcore_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dextras.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dextras_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dinput.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dinput_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dlogic.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquick.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquick_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickextras.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickinput.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickrender.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3drender.pri \
		../miniconda2/mkspecs/modules/qt_lib_3drender_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_bluetooth.pri \
		../miniconda2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_charts.pri \
		../miniconda2/mkspecs/modules/qt_lib_charts_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_concurrent.pri \
		../miniconda2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_core.pri \
		../miniconda2/mkspecs/modules/qt_lib_core_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_datavisualization.pri \
		../miniconda2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_dbus.pri \
		../miniconda2/mkspecs/modules/qt_lib_dbus_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_designer.pri \
		../miniconda2/mkspecs/modules/qt_lib_designer_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_egl_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_fb_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_gamepad.pri \
		../miniconda2/mkspecs/modules/qt_lib_gamepad_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_glx_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_gui.pri \
		../miniconda2/mkspecs/modules/qt_lib_gui_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_help.pri \
		../miniconda2/mkspecs/modules/qt_lib_help_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_input_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_location.pri \
		../miniconda2/mkspecs/modules/qt_lib_location_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_multimedia.pri \
		../miniconda2/mkspecs/modules/qt_lib_multimedia_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../miniconda2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_network.pri \
		../miniconda2/mkspecs/modules/qt_lib_network_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_networkauth.pri \
		../miniconda2/mkspecs/modules/qt_lib_networkauth_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_nfc.pri \
		../miniconda2/mkspecs/modules/qt_lib_nfc_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_opengl.pri \
		../miniconda2/mkspecs/modules/qt_lib_opengl_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_openglextensions.pri \
		../miniconda2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_positioning.pri \
		../miniconda2/mkspecs/modules/qt_lib_positioning_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_printsupport.pri \
		../miniconda2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_purchasing.pri \
		../miniconda2/mkspecs/modules/qt_lib_purchasing_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_qml.pri \
		../miniconda2/mkspecs/modules/qt_lib_qml_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_qmltest.pri \
		../miniconda2/mkspecs/modules/qt_lib_qmltest_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_quick.pri \
		../miniconda2/mkspecs/modules/qt_lib_quick_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../miniconda2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_quickwidgets.pri \
		../miniconda2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_remoteobjects.pri \
		../miniconda2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_repparser.pri \
		../miniconda2/mkspecs/modules/qt_lib_repparser_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_script.pri \
		../miniconda2/mkspecs/modules/qt_lib_script_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_scripttools.pri \
		../miniconda2/mkspecs/modules/qt_lib_scripttools_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_scxml.pri \
		../miniconda2/mkspecs/modules/qt_lib_scxml_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_sensors.pri \
		../miniconda2/mkspecs/modules/qt_lib_sensors_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_serialbus.pri \
		../miniconda2/mkspecs/modules/qt_lib_serialbus_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_serialport.pri \
		../miniconda2/mkspecs/modules/qt_lib_serialport_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_service_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_sql.pri \
		../miniconda2/mkspecs/modules/qt_lib_sql_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_svg.pri \
		../miniconda2/mkspecs/modules/qt_lib_svg_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_testlib.pri \
		../miniconda2/mkspecs/modules/qt_lib_testlib_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_texttospeech.pri \
		../miniconda2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_theme_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_uiplugin.pri \
		../miniconda2/mkspecs/modules/qt_lib_uitools.pri \
		../miniconda2/mkspecs/modules/qt_lib_uitools_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_webchannel.pri \
		../miniconda2/mkspecs/modules/qt_lib_webchannel_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_webengine.pri \
		../miniconda2/mkspecs/modules/qt_lib_webengine_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_webenginecore.pri \
		../miniconda2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../miniconda2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_websockets.pri \
		../miniconda2/mkspecs/modules/qt_lib_websockets_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_webview.pri \
		../miniconda2/mkspecs/modules/qt_lib_webview_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_widgets.pri \
		../miniconda2/mkspecs/modules/qt_lib_widgets_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_x11extras.pri \
		../miniconda2/mkspecs/modules/qt_lib_x11extras_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_xml.pri \
		../miniconda2/mkspecs/modules/qt_lib_xml_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../miniconda2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../miniconda2/mkspecs/features/qt_functions.prf \
		../miniconda2/mkspecs/features/qt_config.prf \
		../miniconda2/mkspecs/linux-g++/qmake.conf \
		../miniconda2/mkspecs/features/spec_post.prf \
		../miniconda2/mkspecs/features/exclusive_builds.prf \
		../miniconda2/mkspecs/features/toolchain.prf \
		../miniconda2/mkspecs/features/default_pre.prf \
		../miniconda2/mkspecs/features/resolve_config.prf \
		../miniconda2/mkspecs/features/default_post.prf \
		../miniconda2/mkspecs/features/warn_on.prf \
		../miniconda2/mkspecs/features/qt.prf \
		../miniconda2/mkspecs/features/resources.prf \
		../miniconda2/mkspecs/features/moc.prf \
		../miniconda2/mkspecs/features/unix/opengl.prf \
		../miniconda2/mkspecs/features/uic.prf \
		../miniconda2/mkspecs/features/unix/thread.prf \
		../miniconda2/mkspecs/features/qmake_use.prf \
		../miniconda2/mkspecs/features/file_copies.prf \
		../miniconda2/mkspecs/features/testcase_targets.prf \
		../miniconda2/mkspecs/features/exceptions.prf \
		../miniconda2/mkspecs/features/yacc.prf \
		../miniconda2/mkspecs/features/lex.prf \
		udptcp.pro mainwindow.h \
		server.h \
		client.h main.cpp \
		mainwindow.cpp \
		server.cpp \
		client.cpp
QMAKE_TARGET  = udptcp
DESTDIR       = 
TARGET        = udptcp


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: udptcp.pro ../miniconda2/mkspecs/linux-g++/qmake.conf ../miniconda2/mkspecs/features/spec_pre.prf \
		../miniconda2/mkspecs/common/unix.conf \
		../miniconda2/mkspecs/common/linux.conf \
		../miniconda2/mkspecs/common/sanitize.conf \
		../miniconda2/mkspecs/common/gcc-base.conf \
		../miniconda2/mkspecs/common/gcc-base-unix.conf \
		../miniconda2/mkspecs/common/g++-base.conf \
		../miniconda2/mkspecs/common/g++-unix.conf \
		../miniconda2/mkspecs/qconfig.pri \
		../miniconda2/mkspecs/modules/qt_lib_3danimation.pri \
		../miniconda2/mkspecs/modules/qt_lib_3danimation_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dcore.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dcore_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dextras.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dextras_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dinput.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dinput_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dlogic.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquick.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquick_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickextras.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickinput.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickrender.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../miniconda2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_3drender.pri \
		../miniconda2/mkspecs/modules/qt_lib_3drender_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_bluetooth.pri \
		../miniconda2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_charts.pri \
		../miniconda2/mkspecs/modules/qt_lib_charts_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_concurrent.pri \
		../miniconda2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_core.pri \
		../miniconda2/mkspecs/modules/qt_lib_core_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_datavisualization.pri \
		../miniconda2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_dbus.pri \
		../miniconda2/mkspecs/modules/qt_lib_dbus_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_designer.pri \
		../miniconda2/mkspecs/modules/qt_lib_designer_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_egl_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_fb_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_gamepad.pri \
		../miniconda2/mkspecs/modules/qt_lib_gamepad_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_glx_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_gui.pri \
		../miniconda2/mkspecs/modules/qt_lib_gui_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_help.pri \
		../miniconda2/mkspecs/modules/qt_lib_help_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_input_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_location.pri \
		../miniconda2/mkspecs/modules/qt_lib_location_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_multimedia.pri \
		../miniconda2/mkspecs/modules/qt_lib_multimedia_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../miniconda2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_network.pri \
		../miniconda2/mkspecs/modules/qt_lib_network_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_networkauth.pri \
		../miniconda2/mkspecs/modules/qt_lib_networkauth_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_nfc.pri \
		../miniconda2/mkspecs/modules/qt_lib_nfc_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_opengl.pri \
		../miniconda2/mkspecs/modules/qt_lib_opengl_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_openglextensions.pri \
		../miniconda2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_positioning.pri \
		../miniconda2/mkspecs/modules/qt_lib_positioning_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_printsupport.pri \
		../miniconda2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_purchasing.pri \
		../miniconda2/mkspecs/modules/qt_lib_purchasing_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_qml.pri \
		../miniconda2/mkspecs/modules/qt_lib_qml_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_qmltest.pri \
		../miniconda2/mkspecs/modules/qt_lib_qmltest_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_quick.pri \
		../miniconda2/mkspecs/modules/qt_lib_quick_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../miniconda2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_quickwidgets.pri \
		../miniconda2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_remoteobjects.pri \
		../miniconda2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_repparser.pri \
		../miniconda2/mkspecs/modules/qt_lib_repparser_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_script.pri \
		../miniconda2/mkspecs/modules/qt_lib_script_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_scripttools.pri \
		../miniconda2/mkspecs/modules/qt_lib_scripttools_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_scxml.pri \
		../miniconda2/mkspecs/modules/qt_lib_scxml_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_sensors.pri \
		../miniconda2/mkspecs/modules/qt_lib_sensors_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_serialbus.pri \
		../miniconda2/mkspecs/modules/qt_lib_serialbus_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_serialport.pri \
		../miniconda2/mkspecs/modules/qt_lib_serialport_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_service_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_sql.pri \
		../miniconda2/mkspecs/modules/qt_lib_sql_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_svg.pri \
		../miniconda2/mkspecs/modules/qt_lib_svg_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_testlib.pri \
		../miniconda2/mkspecs/modules/qt_lib_testlib_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_texttospeech.pri \
		../miniconda2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_theme_support_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_uiplugin.pri \
		../miniconda2/mkspecs/modules/qt_lib_uitools.pri \
		../miniconda2/mkspecs/modules/qt_lib_uitools_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_webchannel.pri \
		../miniconda2/mkspecs/modules/qt_lib_webchannel_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_webengine.pri \
		../miniconda2/mkspecs/modules/qt_lib_webengine_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_webenginecore.pri \
		../miniconda2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../miniconda2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_websockets.pri \
		../miniconda2/mkspecs/modules/qt_lib_websockets_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_webview.pri \
		../miniconda2/mkspecs/modules/qt_lib_webview_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_widgets.pri \
		../miniconda2/mkspecs/modules/qt_lib_widgets_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_x11extras.pri \
		../miniconda2/mkspecs/modules/qt_lib_x11extras_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_xml.pri \
		../miniconda2/mkspecs/modules/qt_lib_xml_private.pri \
		../miniconda2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../miniconda2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../miniconda2/mkspecs/features/qt_functions.prf \
		../miniconda2/mkspecs/features/qt_config.prf \
		../miniconda2/mkspecs/linux-g++/qmake.conf \
		../miniconda2/mkspecs/features/spec_post.prf \
		../miniconda2/mkspecs/features/exclusive_builds.prf \
		../miniconda2/mkspecs/features/toolchain.prf \
		../miniconda2/mkspecs/features/default_pre.prf \
		../miniconda2/mkspecs/features/resolve_config.prf \
		../miniconda2/mkspecs/features/default_post.prf \
		../miniconda2/mkspecs/features/warn_on.prf \
		../miniconda2/mkspecs/features/qt.prf \
		../miniconda2/mkspecs/features/resources.prf \
		../miniconda2/mkspecs/features/moc.prf \
		../miniconda2/mkspecs/features/unix/opengl.prf \
		../miniconda2/mkspecs/features/uic.prf \
		../miniconda2/mkspecs/features/unix/thread.prf \
		../miniconda2/mkspecs/features/qmake_use.prf \
		../miniconda2/mkspecs/features/file_copies.prf \
		../miniconda2/mkspecs/features/testcase_targets.prf \
		../miniconda2/mkspecs/features/exceptions.prf \
		../miniconda2/mkspecs/features/yacc.prf \
		../miniconda2/mkspecs/features/lex.prf \
		udptcp.pro \
		../miniconda2/lib/libQt5Widgets.prl \
		../miniconda2/lib/libQt5Gui.prl \
		../miniconda2/lib/libQt5Network.prl \
		../miniconda2/lib/libQt5Core.prl
	$(QMAKE) -o Makefile udptcp.pro
../miniconda2/mkspecs/features/spec_pre.prf:
../miniconda2/mkspecs/common/unix.conf:
../miniconda2/mkspecs/common/linux.conf:
../miniconda2/mkspecs/common/sanitize.conf:
../miniconda2/mkspecs/common/gcc-base.conf:
../miniconda2/mkspecs/common/gcc-base-unix.conf:
../miniconda2/mkspecs/common/g++-base.conf:
../miniconda2/mkspecs/common/g++-unix.conf:
../miniconda2/mkspecs/qconfig.pri:
../miniconda2/mkspecs/modules/qt_lib_3danimation.pri:
../miniconda2/mkspecs/modules/qt_lib_3danimation_private.pri:
../miniconda2/mkspecs/modules/qt_lib_3dcore.pri:
../miniconda2/mkspecs/modules/qt_lib_3dcore_private.pri:
../miniconda2/mkspecs/modules/qt_lib_3dextras.pri:
../miniconda2/mkspecs/modules/qt_lib_3dextras_private.pri:
../miniconda2/mkspecs/modules/qt_lib_3dinput.pri:
../miniconda2/mkspecs/modules/qt_lib_3dinput_private.pri:
../miniconda2/mkspecs/modules/qt_lib_3dlogic.pri:
../miniconda2/mkspecs/modules/qt_lib_3dlogic_private.pri:
../miniconda2/mkspecs/modules/qt_lib_3dquick.pri:
../miniconda2/mkspecs/modules/qt_lib_3dquick_private.pri:
../miniconda2/mkspecs/modules/qt_lib_3dquickanimation.pri:
../miniconda2/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../miniconda2/mkspecs/modules/qt_lib_3dquickextras.pri:
../miniconda2/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../miniconda2/mkspecs/modules/qt_lib_3dquickinput.pri:
../miniconda2/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../miniconda2/mkspecs/modules/qt_lib_3dquickrender.pri:
../miniconda2/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../miniconda2/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../miniconda2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../miniconda2/mkspecs/modules/qt_lib_3drender.pri:
../miniconda2/mkspecs/modules/qt_lib_3drender_private.pri:
../miniconda2/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../miniconda2/mkspecs/modules/qt_lib_bluetooth.pri:
../miniconda2/mkspecs/modules/qt_lib_bluetooth_private.pri:
../miniconda2/mkspecs/modules/qt_lib_bootstrap_private.pri:
../miniconda2/mkspecs/modules/qt_lib_charts.pri:
../miniconda2/mkspecs/modules/qt_lib_charts_private.pri:
../miniconda2/mkspecs/modules/qt_lib_concurrent.pri:
../miniconda2/mkspecs/modules/qt_lib_concurrent_private.pri:
../miniconda2/mkspecs/modules/qt_lib_core.pri:
../miniconda2/mkspecs/modules/qt_lib_core_private.pri:
../miniconda2/mkspecs/modules/qt_lib_datavisualization.pri:
../miniconda2/mkspecs/modules/qt_lib_datavisualization_private.pri:
../miniconda2/mkspecs/modules/qt_lib_dbus.pri:
../miniconda2/mkspecs/modules/qt_lib_dbus_private.pri:
../miniconda2/mkspecs/modules/qt_lib_designer.pri:
../miniconda2/mkspecs/modules/qt_lib_designer_private.pri:
../miniconda2/mkspecs/modules/qt_lib_designercomponents_private.pri:
../miniconda2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../miniconda2/mkspecs/modules/qt_lib_egl_support_private.pri:
../miniconda2/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../miniconda2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../miniconda2/mkspecs/modules/qt_lib_fb_support_private.pri:
../miniconda2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../miniconda2/mkspecs/modules/qt_lib_gamepad.pri:
../miniconda2/mkspecs/modules/qt_lib_gamepad_private.pri:
../miniconda2/mkspecs/modules/qt_lib_glx_support_private.pri:
../miniconda2/mkspecs/modules/qt_lib_gui.pri:
../miniconda2/mkspecs/modules/qt_lib_gui_private.pri:
../miniconda2/mkspecs/modules/qt_lib_help.pri:
../miniconda2/mkspecs/modules/qt_lib_help_private.pri:
../miniconda2/mkspecs/modules/qt_lib_input_support_private.pri:
../miniconda2/mkspecs/modules/qt_lib_location.pri:
../miniconda2/mkspecs/modules/qt_lib_location_private.pri:
../miniconda2/mkspecs/modules/qt_lib_multimedia.pri:
../miniconda2/mkspecs/modules/qt_lib_multimedia_private.pri:
../miniconda2/mkspecs/modules/qt_lib_multimediawidgets.pri:
../miniconda2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../miniconda2/mkspecs/modules/qt_lib_network.pri:
../miniconda2/mkspecs/modules/qt_lib_network_private.pri:
../miniconda2/mkspecs/modules/qt_lib_networkauth.pri:
../miniconda2/mkspecs/modules/qt_lib_networkauth_private.pri:
../miniconda2/mkspecs/modules/qt_lib_nfc.pri:
../miniconda2/mkspecs/modules/qt_lib_nfc_private.pri:
../miniconda2/mkspecs/modules/qt_lib_opengl.pri:
../miniconda2/mkspecs/modules/qt_lib_opengl_private.pri:
../miniconda2/mkspecs/modules/qt_lib_openglextensions.pri:
../miniconda2/mkspecs/modules/qt_lib_openglextensions_private.pri:
../miniconda2/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../miniconda2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../miniconda2/mkspecs/modules/qt_lib_positioning.pri:
../miniconda2/mkspecs/modules/qt_lib_positioning_private.pri:
../miniconda2/mkspecs/modules/qt_lib_printsupport.pri:
../miniconda2/mkspecs/modules/qt_lib_printsupport_private.pri:
../miniconda2/mkspecs/modules/qt_lib_purchasing.pri:
../miniconda2/mkspecs/modules/qt_lib_purchasing_private.pri:
../miniconda2/mkspecs/modules/qt_lib_qml.pri:
../miniconda2/mkspecs/modules/qt_lib_qml_private.pri:
../miniconda2/mkspecs/modules/qt_lib_qmldebug_private.pri:
../miniconda2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../miniconda2/mkspecs/modules/qt_lib_qmltest.pri:
../miniconda2/mkspecs/modules/qt_lib_qmltest_private.pri:
../miniconda2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../miniconda2/mkspecs/modules/qt_lib_quick.pri:
../miniconda2/mkspecs/modules/qt_lib_quick_private.pri:
../miniconda2/mkspecs/modules/qt_lib_quickcontrols2.pri:
../miniconda2/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../miniconda2/mkspecs/modules/qt_lib_quickparticles_private.pri:
../miniconda2/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../miniconda2/mkspecs/modules/qt_lib_quickwidgets.pri:
../miniconda2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../miniconda2/mkspecs/modules/qt_lib_remoteobjects.pri:
../miniconda2/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../miniconda2/mkspecs/modules/qt_lib_repparser.pri:
../miniconda2/mkspecs/modules/qt_lib_repparser_private.pri:
../miniconda2/mkspecs/modules/qt_lib_script.pri:
../miniconda2/mkspecs/modules/qt_lib_script_private.pri:
../miniconda2/mkspecs/modules/qt_lib_scripttools.pri:
../miniconda2/mkspecs/modules/qt_lib_scripttools_private.pri:
../miniconda2/mkspecs/modules/qt_lib_scxml.pri:
../miniconda2/mkspecs/modules/qt_lib_scxml_private.pri:
../miniconda2/mkspecs/modules/qt_lib_sensors.pri:
../miniconda2/mkspecs/modules/qt_lib_sensors_private.pri:
../miniconda2/mkspecs/modules/qt_lib_serialbus.pri:
../miniconda2/mkspecs/modules/qt_lib_serialbus_private.pri:
../miniconda2/mkspecs/modules/qt_lib_serialport.pri:
../miniconda2/mkspecs/modules/qt_lib_serialport_private.pri:
../miniconda2/mkspecs/modules/qt_lib_service_support_private.pri:
../miniconda2/mkspecs/modules/qt_lib_sql.pri:
../miniconda2/mkspecs/modules/qt_lib_sql_private.pri:
../miniconda2/mkspecs/modules/qt_lib_svg.pri:
../miniconda2/mkspecs/modules/qt_lib_svg_private.pri:
../miniconda2/mkspecs/modules/qt_lib_testlib.pri:
../miniconda2/mkspecs/modules/qt_lib_testlib_private.pri:
../miniconda2/mkspecs/modules/qt_lib_texttospeech.pri:
../miniconda2/mkspecs/modules/qt_lib_texttospeech_private.pri:
../miniconda2/mkspecs/modules/qt_lib_theme_support_private.pri:
../miniconda2/mkspecs/modules/qt_lib_uiplugin.pri:
../miniconda2/mkspecs/modules/qt_lib_uitools.pri:
../miniconda2/mkspecs/modules/qt_lib_uitools_private.pri:
../miniconda2/mkspecs/modules/qt_lib_webchannel.pri:
../miniconda2/mkspecs/modules/qt_lib_webchannel_private.pri:
../miniconda2/mkspecs/modules/qt_lib_webengine.pri:
../miniconda2/mkspecs/modules/qt_lib_webengine_private.pri:
../miniconda2/mkspecs/modules/qt_lib_webenginecore.pri:
../miniconda2/mkspecs/modules/qt_lib_webenginecore_private.pri:
../miniconda2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../miniconda2/mkspecs/modules/qt_lib_webenginewidgets.pri:
../miniconda2/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../miniconda2/mkspecs/modules/qt_lib_websockets.pri:
../miniconda2/mkspecs/modules/qt_lib_websockets_private.pri:
../miniconda2/mkspecs/modules/qt_lib_webview.pri:
../miniconda2/mkspecs/modules/qt_lib_webview_private.pri:
../miniconda2/mkspecs/modules/qt_lib_widgets.pri:
../miniconda2/mkspecs/modules/qt_lib_widgets_private.pri:
../miniconda2/mkspecs/modules/qt_lib_x11extras.pri:
../miniconda2/mkspecs/modules/qt_lib_x11extras_private.pri:
../miniconda2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../miniconda2/mkspecs/modules/qt_lib_xml.pri:
../miniconda2/mkspecs/modules/qt_lib_xml_private.pri:
../miniconda2/mkspecs/modules/qt_lib_xmlpatterns.pri:
../miniconda2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../miniconda2/mkspecs/features/qt_functions.prf:
../miniconda2/mkspecs/features/qt_config.prf:
../miniconda2/mkspecs/linux-g++/qmake.conf:
../miniconda2/mkspecs/features/spec_post.prf:
../miniconda2/mkspecs/features/exclusive_builds.prf:
../miniconda2/mkspecs/features/toolchain.prf:
../miniconda2/mkspecs/features/default_pre.prf:
../miniconda2/mkspecs/features/resolve_config.prf:
../miniconda2/mkspecs/features/default_post.prf:
../miniconda2/mkspecs/features/warn_on.prf:
../miniconda2/mkspecs/features/qt.prf:
../miniconda2/mkspecs/features/resources.prf:
../miniconda2/mkspecs/features/moc.prf:
../miniconda2/mkspecs/features/unix/opengl.prf:
../miniconda2/mkspecs/features/uic.prf:
../miniconda2/mkspecs/features/unix/thread.prf:
../miniconda2/mkspecs/features/qmake_use.prf:
../miniconda2/mkspecs/features/file_copies.prf:
../miniconda2/mkspecs/features/testcase_targets.prf:
../miniconda2/mkspecs/features/exceptions.prf:
../miniconda2/mkspecs/features/yacc.prf:
../miniconda2/mkspecs/features/lex.prf:
udptcp.pro:
../miniconda2/lib/libQt5Widgets.prl:
../miniconda2/lib/libQt5Gui.prl:
../miniconda2/lib/libQt5Network.prl:
../miniconda2/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile udptcp.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../miniconda2/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h server.h client.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp server.cpp client.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../miniconda2/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h ../miniconda2/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_server.cpp moc_client.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_server.cpp moc_client.cpp
moc_mainwindow.cpp: ../miniconda2/include/qt/QtWidgets/QMainWindow \
		../miniconda2/include/qt/QtWidgets/qmainwindow.h \
		../miniconda2/include/qt/QtWidgets/qtwidgetsglobal.h \
		../miniconda2/include/qt/QtGui/qtguiglobal.h \
		../miniconda2/include/qt/QtCore/qglobal.h \
		../miniconda2/include/qt/QtCore/qconfig-bootstrapped.h \
		../miniconda2/include/qt/QtCore/qconfig.h \
		../miniconda2/include/qt/QtCore/qtcore-config.h \
		../miniconda2/include/qt/QtCore/qsystemdetection.h \
		../miniconda2/include/qt/QtCore/qprocessordetection.h \
		../miniconda2/include/qt/QtCore/qcompilerdetection.h \
		../miniconda2/include/qt/QtCore/qtypeinfo.h \
		../miniconda2/include/qt/QtCore/qsysinfo.h \
		../miniconda2/include/qt/QtCore/qlogging.h \
		../miniconda2/include/qt/QtCore/qflags.h \
		../miniconda2/include/qt/QtCore/qatomic.h \
		../miniconda2/include/qt/QtCore/qbasicatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../miniconda2/include/qt/QtCore/qgenericatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_cxx11.h \
		../miniconda2/include/qt/QtCore/qatomic_msvc.h \
		../miniconda2/include/qt/QtCore/qglobalstatic.h \
		../miniconda2/include/qt/QtCore/qmutex.h \
		../miniconda2/include/qt/QtCore/qnumeric.h \
		../miniconda2/include/qt/QtCore/qversiontagging.h \
		../miniconda2/include/qt/QtGui/qtgui-config.h \
		../miniconda2/include/qt/QtWidgets/qtwidgets-config.h \
		../miniconda2/include/qt/QtWidgets/qwidget.h \
		../miniconda2/include/qt/QtGui/qwindowdefs.h \
		../miniconda2/include/qt/QtCore/qobjectdefs.h \
		../miniconda2/include/qt/QtCore/qnamespace.h \
		../miniconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../miniconda2/include/qt/QtGui/qwindowdefs_win.h \
		../miniconda2/include/qt/QtCore/qobject.h \
		../miniconda2/include/qt/QtCore/qstring.h \
		../miniconda2/include/qt/QtCore/qchar.h \
		../miniconda2/include/qt/QtCore/qbytearray.h \
		../miniconda2/include/qt/QtCore/qrefcount.h \
		../miniconda2/include/qt/QtCore/qarraydata.h \
		../miniconda2/include/qt/QtCore/qstringbuilder.h \
		../miniconda2/include/qt/QtCore/qlist.h \
		../miniconda2/include/qt/QtCore/qalgorithms.h \
		../miniconda2/include/qt/QtCore/qiterator.h \
		../miniconda2/include/qt/QtCore/qhashfunctions.h \
		../miniconda2/include/qt/QtCore/qpair.h \
		../miniconda2/include/qt/QtCore/qbytearraylist.h \
		../miniconda2/include/qt/QtCore/qstringlist.h \
		../miniconda2/include/qt/QtCore/qregexp.h \
		../miniconda2/include/qt/QtCore/qstringmatcher.h \
		../miniconda2/include/qt/QtCore/qcoreevent.h \
		../miniconda2/include/qt/QtCore/qscopedpointer.h \
		../miniconda2/include/qt/QtCore/qmetatype.h \
		../miniconda2/include/qt/QtCore/qvarlengtharray.h \
		../miniconda2/include/qt/QtCore/qcontainerfwd.h \
		../miniconda2/include/qt/QtCore/qobject_impl.h \
		../miniconda2/include/qt/QtCore/qmargins.h \
		../miniconda2/include/qt/QtGui/qpaintdevice.h \
		../miniconda2/include/qt/QtCore/qrect.h \
		../miniconda2/include/qt/QtCore/qsize.h \
		../miniconda2/include/qt/QtCore/qpoint.h \
		../miniconda2/include/qt/QtGui/qpalette.h \
		../miniconda2/include/qt/QtGui/qcolor.h \
		../miniconda2/include/qt/QtGui/qrgb.h \
		../miniconda2/include/qt/QtGui/qrgba64.h \
		../miniconda2/include/qt/QtGui/qbrush.h \
		../miniconda2/include/qt/QtCore/qvector.h \
		../miniconda2/include/qt/QtGui/qmatrix.h \
		../miniconda2/include/qt/QtGui/qpolygon.h \
		../miniconda2/include/qt/QtGui/qregion.h \
		../miniconda2/include/qt/QtCore/qdatastream.h \
		../miniconda2/include/qt/QtCore/qiodevice.h \
		../miniconda2/include/qt/QtCore/qline.h \
		../miniconda2/include/qt/QtGui/qtransform.h \
		../miniconda2/include/qt/QtGui/qpainterpath.h \
		../miniconda2/include/qt/QtGui/qimage.h \
		../miniconda2/include/qt/QtGui/qpixelformat.h \
		../miniconda2/include/qt/QtGui/qpixmap.h \
		../miniconda2/include/qt/QtCore/qsharedpointer.h \
		../miniconda2/include/qt/QtCore/qshareddata.h \
		../miniconda2/include/qt/QtCore/qhash.h \
		../miniconda2/include/qt/QtCore/qsharedpointer_impl.h \
		../miniconda2/include/qt/QtGui/qfont.h \
		../miniconda2/include/qt/QtGui/qfontmetrics.h \
		../miniconda2/include/qt/QtGui/qfontinfo.h \
		../miniconda2/include/qt/QtWidgets/qsizepolicy.h \
		../miniconda2/include/qt/QtGui/qcursor.h \
		../miniconda2/include/qt/QtGui/qkeysequence.h \
		../miniconda2/include/qt/QtGui/qevent.h \
		../miniconda2/include/qt/QtCore/qvariant.h \
		../miniconda2/include/qt/QtCore/qmap.h \
		../miniconda2/include/qt/QtCore/qdebug.h \
		../miniconda2/include/qt/QtCore/qtextstream.h \
		../miniconda2/include/qt/QtCore/qlocale.h \
		../miniconda2/include/qt/QtCore/qset.h \
		../miniconda2/include/qt/QtCore/qcontiguouscache.h \
		../miniconda2/include/qt/QtCore/qurl.h \
		../miniconda2/include/qt/QtCore/qurlquery.h \
		../miniconda2/include/qt/QtCore/qfile.h \
		../miniconda2/include/qt/QtCore/qfiledevice.h \
		../miniconda2/include/qt/QtGui/qvector2d.h \
		../miniconda2/include/qt/QtGui/qtouchdevice.h \
		../miniconda2/include/qt/QtWidgets/qtabwidget.h \
		../miniconda2/include/qt/QtGui/qicon.h \
		client.h \
		../miniconda2/include/qt/QtCore/QObject \
		../miniconda2/include/qt/QtCore/QDebug \
		../miniconda2/include/qt/QtWidgets/QFileDialog \
		../miniconda2/include/qt/QtWidgets/qfiledialog.h \
		../miniconda2/include/qt/QtCore/qdir.h \
		../miniconda2/include/qt/QtCore/qfileinfo.h \
		../miniconda2/include/qt/QtWidgets/qdialog.h \
		../miniconda2/include/qt/QtWidgets/QDockWidget \
		../miniconda2/include/qt/QtWidgets/qdockwidget.h \
		../miniconda2/include/qt/QtWidgets/QMessageBox \
		../miniconda2/include/qt/QtWidgets/qmessagebox.h \
		../miniconda2/include/qt/QtWidgets/QGraphicsScene \
		../miniconda2/include/qt/QtWidgets/qgraphicsscene.h \
		../miniconda2/include/qt/QtGui/qpen.h \
		../miniconda2/include/qt/QtCore/QBuffer \
		../miniconda2/include/qt/QtCore/qbuffer.h \
		../miniconda2/include/qt/QtWidgets/QDialog \
		../miniconda2/include/qt/QtCore/QString \
		../miniconda2/include/qt/QtCore/QFile \
		../miniconda2/include/qt/QtNetwork/QTcpSocket \
		../miniconda2/include/qt/QtNetwork/qtcpsocket.h \
		../miniconda2/include/qt/QtNetwork/qtnetworkglobal.h \
		../miniconda2/include/qt/QtNetwork/qtnetwork-config.h \
		../miniconda2/include/qt/QtNetwork/qabstractsocket.h \
		../miniconda2/include/qt/QtNetwork/QUdpSocket \
		../miniconda2/include/qt/QtNetwork/qudpsocket.h \
		../miniconda2/include/qt/QtNetwork/qhostaddress.h \
		../miniconda2/include/qt/QtNetwork/QTcpServer \
		../miniconda2/include/qt/QtNetwork/qtcpserver.h \
		../miniconda2/include/qt/QtNetwork/QNetworkInterface \
		../miniconda2/include/qt/QtNetwork/qnetworkinterface.h \
		../miniconda2/include/qt/QtNetwork/QNetworkConfigurationManager \
		../miniconda2/include/qt/QtNetwork/qnetworkconfigmanager.h \
		../miniconda2/include/qt/QtNetwork/qnetworkconfiguration.h \
		../miniconda2/include/qt/QtNetwork/QNetworkSession \
		../miniconda2/include/qt/QtNetwork/qnetworksession.h \
		../miniconda2/include/qt/QtCore/QSettings \
		../miniconda2/include/qt/QtCore/qsettings.h \
		server.h \
		mainwindow.h \
		moc_predefs.h \
		../miniconda2/bin/moc
	/home/joaovfabri/miniconda2/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/joaovfabri/miniconda2/mkspecs/linux-g++ -I/home/joaovfabri/udptcp -I/home/joaovfabri/miniconda2/include/qt -I/home/joaovfabri/miniconda2/include/qt/QtWidgets -I/home/joaovfabri/miniconda2/include/qt/QtGui -I/home/joaovfabri/miniconda2/include/qt/QtNetwork -I/home/joaovfabri/miniconda2/include/qt/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_server.cpp: ../miniconda2/include/qt/QtCore/QDebug \
		../miniconda2/include/qt/QtCore/qdebug.h \
		../miniconda2/include/qt/QtCore/qalgorithms.h \
		../miniconda2/include/qt/QtCore/qglobal.h \
		../miniconda2/include/qt/QtCore/qconfig-bootstrapped.h \
		../miniconda2/include/qt/QtCore/qconfig.h \
		../miniconda2/include/qt/QtCore/qtcore-config.h \
		../miniconda2/include/qt/QtCore/qsystemdetection.h \
		../miniconda2/include/qt/QtCore/qprocessordetection.h \
		../miniconda2/include/qt/QtCore/qcompilerdetection.h \
		../miniconda2/include/qt/QtCore/qtypeinfo.h \
		../miniconda2/include/qt/QtCore/qsysinfo.h \
		../miniconda2/include/qt/QtCore/qlogging.h \
		../miniconda2/include/qt/QtCore/qflags.h \
		../miniconda2/include/qt/QtCore/qatomic.h \
		../miniconda2/include/qt/QtCore/qbasicatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../miniconda2/include/qt/QtCore/qgenericatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_cxx11.h \
		../miniconda2/include/qt/QtCore/qatomic_msvc.h \
		../miniconda2/include/qt/QtCore/qglobalstatic.h \
		../miniconda2/include/qt/QtCore/qmutex.h \
		../miniconda2/include/qt/QtCore/qnumeric.h \
		../miniconda2/include/qt/QtCore/qversiontagging.h \
		../miniconda2/include/qt/QtCore/qhash.h \
		../miniconda2/include/qt/QtCore/qchar.h \
		../miniconda2/include/qt/QtCore/qiterator.h \
		../miniconda2/include/qt/QtCore/qlist.h \
		../miniconda2/include/qt/QtCore/qrefcount.h \
		../miniconda2/include/qt/QtCore/qarraydata.h \
		../miniconda2/include/qt/QtCore/qhashfunctions.h \
		../miniconda2/include/qt/QtCore/qpair.h \
		../miniconda2/include/qt/QtCore/qbytearraylist.h \
		../miniconda2/include/qt/QtCore/qbytearray.h \
		../miniconda2/include/qt/QtCore/qnamespace.h \
		../miniconda2/include/qt/QtCore/qstring.h \
		../miniconda2/include/qt/QtCore/qstringbuilder.h \
		../miniconda2/include/qt/QtCore/qstringlist.h \
		../miniconda2/include/qt/QtCore/qregexp.h \
		../miniconda2/include/qt/QtCore/qstringmatcher.h \
		../miniconda2/include/qt/QtCore/qmap.h \
		../miniconda2/include/qt/QtCore/qtextstream.h \
		../miniconda2/include/qt/QtCore/qiodevice.h \
		../miniconda2/include/qt/QtCore/qobject.h \
		../miniconda2/include/qt/QtCore/qobjectdefs.h \
		../miniconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../miniconda2/include/qt/QtCore/qcoreevent.h \
		../miniconda2/include/qt/QtCore/qscopedpointer.h \
		../miniconda2/include/qt/QtCore/qmetatype.h \
		../miniconda2/include/qt/QtCore/qvarlengtharray.h \
		../miniconda2/include/qt/QtCore/qcontainerfwd.h \
		../miniconda2/include/qt/QtCore/qobject_impl.h \
		../miniconda2/include/qt/QtCore/qlocale.h \
		../miniconda2/include/qt/QtCore/qvariant.h \
		../miniconda2/include/qt/QtCore/qshareddata.h \
		../miniconda2/include/qt/QtCore/qvector.h \
		../miniconda2/include/qt/QtCore/qpoint.h \
		../miniconda2/include/qt/QtCore/qset.h \
		../miniconda2/include/qt/QtCore/qcontiguouscache.h \
		../miniconda2/include/qt/QtCore/qsharedpointer.h \
		../miniconda2/include/qt/QtCore/qsharedpointer_impl.h \
		../miniconda2/include/qt/QtWidgets/QFileDialog \
		../miniconda2/include/qt/QtWidgets/qfiledialog.h \
		../miniconda2/include/qt/QtWidgets/qtwidgetsglobal.h \
		../miniconda2/include/qt/QtGui/qtguiglobal.h \
		../miniconda2/include/qt/QtGui/qtgui-config.h \
		../miniconda2/include/qt/QtWidgets/qtwidgets-config.h \
		../miniconda2/include/qt/QtCore/qdir.h \
		../miniconda2/include/qt/QtCore/qfileinfo.h \
		../miniconda2/include/qt/QtCore/qfile.h \
		../miniconda2/include/qt/QtCore/qfiledevice.h \
		../miniconda2/include/qt/QtCore/qurl.h \
		../miniconda2/include/qt/QtCore/qurlquery.h \
		../miniconda2/include/qt/QtWidgets/qdialog.h \
		../miniconda2/include/qt/QtWidgets/qwidget.h \
		../miniconda2/include/qt/QtGui/qwindowdefs.h \
		../miniconda2/include/qt/QtGui/qwindowdefs_win.h \
		../miniconda2/include/qt/QtCore/qmargins.h \
		../miniconda2/include/qt/QtGui/qpaintdevice.h \
		../miniconda2/include/qt/QtCore/qrect.h \
		../miniconda2/include/qt/QtCore/qsize.h \
		../miniconda2/include/qt/QtGui/qpalette.h \
		../miniconda2/include/qt/QtGui/qcolor.h \
		../miniconda2/include/qt/QtGui/qrgb.h \
		../miniconda2/include/qt/QtGui/qrgba64.h \
		../miniconda2/include/qt/QtGui/qbrush.h \
		../miniconda2/include/qt/QtGui/qmatrix.h \
		../miniconda2/include/qt/QtGui/qpolygon.h \
		../miniconda2/include/qt/QtGui/qregion.h \
		../miniconda2/include/qt/QtCore/qdatastream.h \
		../miniconda2/include/qt/QtCore/qline.h \
		../miniconda2/include/qt/QtGui/qtransform.h \
		../miniconda2/include/qt/QtGui/qpainterpath.h \
		../miniconda2/include/qt/QtGui/qimage.h \
		../miniconda2/include/qt/QtGui/qpixelformat.h \
		../miniconda2/include/qt/QtGui/qpixmap.h \
		../miniconda2/include/qt/QtGui/qfont.h \
		../miniconda2/include/qt/QtGui/qfontmetrics.h \
		../miniconda2/include/qt/QtGui/qfontinfo.h \
		../miniconda2/include/qt/QtWidgets/qsizepolicy.h \
		../miniconda2/include/qt/QtGui/qcursor.h \
		../miniconda2/include/qt/QtGui/qkeysequence.h \
		../miniconda2/include/qt/QtGui/qevent.h \
		../miniconda2/include/qt/QtGui/qvector2d.h \
		../miniconda2/include/qt/QtGui/qtouchdevice.h \
		../miniconda2/include/qt/QtWidgets/QDockWidget \
		../miniconda2/include/qt/QtWidgets/qdockwidget.h \
		../miniconda2/include/qt/QtWidgets/QMessageBox \
		../miniconda2/include/qt/QtWidgets/qmessagebox.h \
		../miniconda2/include/qt/QtWidgets/QGraphicsScene \
		../miniconda2/include/qt/QtWidgets/qgraphicsscene.h \
		../miniconda2/include/qt/QtGui/qpen.h \
		../miniconda2/include/qt/QtCore/QBuffer \
		../miniconda2/include/qt/QtCore/qbuffer.h \
		../miniconda2/include/qt/QtWidgets/QDialog \
		../miniconda2/include/qt/QtCore/QString \
		../miniconda2/include/qt/QtCore/QObject \
		../miniconda2/include/qt/QtCore/QFile \
		../miniconda2/include/qt/QtNetwork/QTcpSocket \
		../miniconda2/include/qt/QtNetwork/qtcpsocket.h \
		../miniconda2/include/qt/QtNetwork/qtnetworkglobal.h \
		../miniconda2/include/qt/QtNetwork/qtnetwork-config.h \
		../miniconda2/include/qt/QtNetwork/qabstractsocket.h \
		../miniconda2/include/qt/QtNetwork/QUdpSocket \
		../miniconda2/include/qt/QtNetwork/qudpsocket.h \
		../miniconda2/include/qt/QtNetwork/qhostaddress.h \
		../miniconda2/include/qt/QtNetwork/QTcpServer \
		../miniconda2/include/qt/QtNetwork/qtcpserver.h \
		../miniconda2/include/qt/QtNetwork/QNetworkInterface \
		../miniconda2/include/qt/QtNetwork/qnetworkinterface.h \
		../miniconda2/include/qt/QtNetwork/QNetworkConfigurationManager \
		../miniconda2/include/qt/QtNetwork/qnetworkconfigmanager.h \
		../miniconda2/include/qt/QtNetwork/qnetworkconfiguration.h \
		../miniconda2/include/qt/QtNetwork/QNetworkSession \
		../miniconda2/include/qt/QtNetwork/qnetworksession.h \
		../miniconda2/include/qt/QtCore/QSettings \
		../miniconda2/include/qt/QtCore/qsettings.h \
		server.h \
		moc_predefs.h \
		../miniconda2/bin/moc
	/home/joaovfabri/miniconda2/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/joaovfabri/miniconda2/mkspecs/linux-g++ -I/home/joaovfabri/udptcp -I/home/joaovfabri/miniconda2/include/qt -I/home/joaovfabri/miniconda2/include/qt/QtWidgets -I/home/joaovfabri/miniconda2/include/qt/QtGui -I/home/joaovfabri/miniconda2/include/qt/QtNetwork -I/home/joaovfabri/miniconda2/include/qt/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include server.h -o moc_server.cpp

moc_client.cpp: ../miniconda2/include/qt/QtCore/QObject \
		../miniconda2/include/qt/QtCore/qobject.h \
		../miniconda2/include/qt/QtCore/qobjectdefs.h \
		../miniconda2/include/qt/QtCore/qnamespace.h \
		../miniconda2/include/qt/QtCore/qglobal.h \
		../miniconda2/include/qt/QtCore/qconfig-bootstrapped.h \
		../miniconda2/include/qt/QtCore/qconfig.h \
		../miniconda2/include/qt/QtCore/qtcore-config.h \
		../miniconda2/include/qt/QtCore/qsystemdetection.h \
		../miniconda2/include/qt/QtCore/qprocessordetection.h \
		../miniconda2/include/qt/QtCore/qcompilerdetection.h \
		../miniconda2/include/qt/QtCore/qtypeinfo.h \
		../miniconda2/include/qt/QtCore/qsysinfo.h \
		../miniconda2/include/qt/QtCore/qlogging.h \
		../miniconda2/include/qt/QtCore/qflags.h \
		../miniconda2/include/qt/QtCore/qatomic.h \
		../miniconda2/include/qt/QtCore/qbasicatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../miniconda2/include/qt/QtCore/qgenericatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_cxx11.h \
		../miniconda2/include/qt/QtCore/qatomic_msvc.h \
		../miniconda2/include/qt/QtCore/qglobalstatic.h \
		../miniconda2/include/qt/QtCore/qmutex.h \
		../miniconda2/include/qt/QtCore/qnumeric.h \
		../miniconda2/include/qt/QtCore/qversiontagging.h \
		../miniconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../miniconda2/include/qt/QtCore/qstring.h \
		../miniconda2/include/qt/QtCore/qchar.h \
		../miniconda2/include/qt/QtCore/qbytearray.h \
		../miniconda2/include/qt/QtCore/qrefcount.h \
		../miniconda2/include/qt/QtCore/qarraydata.h \
		../miniconda2/include/qt/QtCore/qstringbuilder.h \
		../miniconda2/include/qt/QtCore/qlist.h \
		../miniconda2/include/qt/QtCore/qalgorithms.h \
		../miniconda2/include/qt/QtCore/qiterator.h \
		../miniconda2/include/qt/QtCore/qhashfunctions.h \
		../miniconda2/include/qt/QtCore/qpair.h \
		../miniconda2/include/qt/QtCore/qbytearraylist.h \
		../miniconda2/include/qt/QtCore/qstringlist.h \
		../miniconda2/include/qt/QtCore/qregexp.h \
		../miniconda2/include/qt/QtCore/qstringmatcher.h \
		../miniconda2/include/qt/QtCore/qcoreevent.h \
		../miniconda2/include/qt/QtCore/qscopedpointer.h \
		../miniconda2/include/qt/QtCore/qmetatype.h \
		../miniconda2/include/qt/QtCore/qvarlengtharray.h \
		../miniconda2/include/qt/QtCore/qcontainerfwd.h \
		../miniconda2/include/qt/QtCore/qobject_impl.h \
		../miniconda2/include/qt/QtCore/QDebug \
		../miniconda2/include/qt/QtCore/qdebug.h \
		../miniconda2/include/qt/QtCore/qhash.h \
		../miniconda2/include/qt/QtCore/qmap.h \
		../miniconda2/include/qt/QtCore/qtextstream.h \
		../miniconda2/include/qt/QtCore/qiodevice.h \
		../miniconda2/include/qt/QtCore/qlocale.h \
		../miniconda2/include/qt/QtCore/qvariant.h \
		../miniconda2/include/qt/QtCore/qshareddata.h \
		../miniconda2/include/qt/QtCore/qvector.h \
		../miniconda2/include/qt/QtCore/qpoint.h \
		../miniconda2/include/qt/QtCore/qset.h \
		../miniconda2/include/qt/QtCore/qcontiguouscache.h \
		../miniconda2/include/qt/QtCore/qsharedpointer.h \
		../miniconda2/include/qt/QtCore/qsharedpointer_impl.h \
		../miniconda2/include/qt/QtWidgets/QFileDialog \
		../miniconda2/include/qt/QtWidgets/qfiledialog.h \
		../miniconda2/include/qt/QtWidgets/qtwidgetsglobal.h \
		../miniconda2/include/qt/QtGui/qtguiglobal.h \
		../miniconda2/include/qt/QtGui/qtgui-config.h \
		../miniconda2/include/qt/QtWidgets/qtwidgets-config.h \
		../miniconda2/include/qt/QtCore/qdir.h \
		../miniconda2/include/qt/QtCore/qfileinfo.h \
		../miniconda2/include/qt/QtCore/qfile.h \
		../miniconda2/include/qt/QtCore/qfiledevice.h \
		../miniconda2/include/qt/QtCore/qurl.h \
		../miniconda2/include/qt/QtCore/qurlquery.h \
		../miniconda2/include/qt/QtWidgets/qdialog.h \
		../miniconda2/include/qt/QtWidgets/qwidget.h \
		../miniconda2/include/qt/QtGui/qwindowdefs.h \
		../miniconda2/include/qt/QtGui/qwindowdefs_win.h \
		../miniconda2/include/qt/QtCore/qmargins.h \
		../miniconda2/include/qt/QtGui/qpaintdevice.h \
		../miniconda2/include/qt/QtCore/qrect.h \
		../miniconda2/include/qt/QtCore/qsize.h \
		../miniconda2/include/qt/QtGui/qpalette.h \
		../miniconda2/include/qt/QtGui/qcolor.h \
		../miniconda2/include/qt/QtGui/qrgb.h \
		../miniconda2/include/qt/QtGui/qrgba64.h \
		../miniconda2/include/qt/QtGui/qbrush.h \
		../miniconda2/include/qt/QtGui/qmatrix.h \
		../miniconda2/include/qt/QtGui/qpolygon.h \
		../miniconda2/include/qt/QtGui/qregion.h \
		../miniconda2/include/qt/QtCore/qdatastream.h \
		../miniconda2/include/qt/QtCore/qline.h \
		../miniconda2/include/qt/QtGui/qtransform.h \
		../miniconda2/include/qt/QtGui/qpainterpath.h \
		../miniconda2/include/qt/QtGui/qimage.h \
		../miniconda2/include/qt/QtGui/qpixelformat.h \
		../miniconda2/include/qt/QtGui/qpixmap.h \
		../miniconda2/include/qt/QtGui/qfont.h \
		../miniconda2/include/qt/QtGui/qfontmetrics.h \
		../miniconda2/include/qt/QtGui/qfontinfo.h \
		../miniconda2/include/qt/QtWidgets/qsizepolicy.h \
		../miniconda2/include/qt/QtGui/qcursor.h \
		../miniconda2/include/qt/QtGui/qkeysequence.h \
		../miniconda2/include/qt/QtGui/qevent.h \
		../miniconda2/include/qt/QtGui/qvector2d.h \
		../miniconda2/include/qt/QtGui/qtouchdevice.h \
		../miniconda2/include/qt/QtWidgets/QDockWidget \
		../miniconda2/include/qt/QtWidgets/qdockwidget.h \
		../miniconda2/include/qt/QtWidgets/QMessageBox \
		../miniconda2/include/qt/QtWidgets/qmessagebox.h \
		../miniconda2/include/qt/QtWidgets/QGraphicsScene \
		../miniconda2/include/qt/QtWidgets/qgraphicsscene.h \
		../miniconda2/include/qt/QtGui/qpen.h \
		../miniconda2/include/qt/QtCore/QBuffer \
		../miniconda2/include/qt/QtCore/qbuffer.h \
		../miniconda2/include/qt/QtWidgets/QDialog \
		../miniconda2/include/qt/QtCore/QString \
		../miniconda2/include/qt/QtCore/QFile \
		../miniconda2/include/qt/QtNetwork/QTcpSocket \
		../miniconda2/include/qt/QtNetwork/qtcpsocket.h \
		../miniconda2/include/qt/QtNetwork/qtnetworkglobal.h \
		../miniconda2/include/qt/QtNetwork/qtnetwork-config.h \
		../miniconda2/include/qt/QtNetwork/qabstractsocket.h \
		../miniconda2/include/qt/QtNetwork/QUdpSocket \
		../miniconda2/include/qt/QtNetwork/qudpsocket.h \
		../miniconda2/include/qt/QtNetwork/qhostaddress.h \
		../miniconda2/include/qt/QtNetwork/QTcpServer \
		../miniconda2/include/qt/QtNetwork/qtcpserver.h \
		../miniconda2/include/qt/QtNetwork/QNetworkInterface \
		../miniconda2/include/qt/QtNetwork/qnetworkinterface.h \
		../miniconda2/include/qt/QtNetwork/QNetworkConfigurationManager \
		../miniconda2/include/qt/QtNetwork/qnetworkconfigmanager.h \
		../miniconda2/include/qt/QtNetwork/qnetworkconfiguration.h \
		../miniconda2/include/qt/QtNetwork/QNetworkSession \
		../miniconda2/include/qt/QtNetwork/qnetworksession.h \
		../miniconda2/include/qt/QtCore/QSettings \
		../miniconda2/include/qt/QtCore/qsettings.h \
		client.h \
		moc_predefs.h \
		../miniconda2/bin/moc
	/home/joaovfabri/miniconda2/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/joaovfabri/miniconda2/mkspecs/linux-g++ -I/home/joaovfabri/udptcp -I/home/joaovfabri/miniconda2/include/qt -I/home/joaovfabri/miniconda2/include/qt/QtWidgets -I/home/joaovfabri/miniconda2/include/qt/QtGui -I/home/joaovfabri/miniconda2/include/qt/QtNetwork -I/home/joaovfabri/miniconda2/include/qt/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include client.h -o moc_client.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../miniconda2/bin/uic
	/home/joaovfabri/miniconda2/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../miniconda2/include/qt/QtWidgets/QMainWindow \
		../miniconda2/include/qt/QtWidgets/qmainwindow.h \
		../miniconda2/include/qt/QtWidgets/qtwidgetsglobal.h \
		../miniconda2/include/qt/QtGui/qtguiglobal.h \
		../miniconda2/include/qt/QtCore/qglobal.h \
		../miniconda2/include/qt/QtCore/qconfig-bootstrapped.h \
		../miniconda2/include/qt/QtCore/qconfig.h \
		../miniconda2/include/qt/QtCore/qtcore-config.h \
		../miniconda2/include/qt/QtCore/qsystemdetection.h \
		../miniconda2/include/qt/QtCore/qprocessordetection.h \
		../miniconda2/include/qt/QtCore/qcompilerdetection.h \
		../miniconda2/include/qt/QtCore/qtypeinfo.h \
		../miniconda2/include/qt/QtCore/qsysinfo.h \
		../miniconda2/include/qt/QtCore/qlogging.h \
		../miniconda2/include/qt/QtCore/qflags.h \
		../miniconda2/include/qt/QtCore/qatomic.h \
		../miniconda2/include/qt/QtCore/qbasicatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../miniconda2/include/qt/QtCore/qgenericatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_cxx11.h \
		../miniconda2/include/qt/QtCore/qatomic_msvc.h \
		../miniconda2/include/qt/QtCore/qglobalstatic.h \
		../miniconda2/include/qt/QtCore/qmutex.h \
		../miniconda2/include/qt/QtCore/qnumeric.h \
		../miniconda2/include/qt/QtCore/qversiontagging.h \
		../miniconda2/include/qt/QtGui/qtgui-config.h \
		../miniconda2/include/qt/QtWidgets/qtwidgets-config.h \
		../miniconda2/include/qt/QtWidgets/qwidget.h \
		../miniconda2/include/qt/QtGui/qwindowdefs.h \
		../miniconda2/include/qt/QtCore/qobjectdefs.h \
		../miniconda2/include/qt/QtCore/qnamespace.h \
		../miniconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../miniconda2/include/qt/QtGui/qwindowdefs_win.h \
		../miniconda2/include/qt/QtCore/qobject.h \
		../miniconda2/include/qt/QtCore/qstring.h \
		../miniconda2/include/qt/QtCore/qchar.h \
		../miniconda2/include/qt/QtCore/qbytearray.h \
		../miniconda2/include/qt/QtCore/qrefcount.h \
		../miniconda2/include/qt/QtCore/qarraydata.h \
		../miniconda2/include/qt/QtCore/qstringbuilder.h \
		../miniconda2/include/qt/QtCore/qlist.h \
		../miniconda2/include/qt/QtCore/qalgorithms.h \
		../miniconda2/include/qt/QtCore/qiterator.h \
		../miniconda2/include/qt/QtCore/qhashfunctions.h \
		../miniconda2/include/qt/QtCore/qpair.h \
		../miniconda2/include/qt/QtCore/qbytearraylist.h \
		../miniconda2/include/qt/QtCore/qstringlist.h \
		../miniconda2/include/qt/QtCore/qregexp.h \
		../miniconda2/include/qt/QtCore/qstringmatcher.h \
		../miniconda2/include/qt/QtCore/qcoreevent.h \
		../miniconda2/include/qt/QtCore/qscopedpointer.h \
		../miniconda2/include/qt/QtCore/qmetatype.h \
		../miniconda2/include/qt/QtCore/qvarlengtharray.h \
		../miniconda2/include/qt/QtCore/qcontainerfwd.h \
		../miniconda2/include/qt/QtCore/qobject_impl.h \
		../miniconda2/include/qt/QtCore/qmargins.h \
		../miniconda2/include/qt/QtGui/qpaintdevice.h \
		../miniconda2/include/qt/QtCore/qrect.h \
		../miniconda2/include/qt/QtCore/qsize.h \
		../miniconda2/include/qt/QtCore/qpoint.h \
		../miniconda2/include/qt/QtGui/qpalette.h \
		../miniconda2/include/qt/QtGui/qcolor.h \
		../miniconda2/include/qt/QtGui/qrgb.h \
		../miniconda2/include/qt/QtGui/qrgba64.h \
		../miniconda2/include/qt/QtGui/qbrush.h \
		../miniconda2/include/qt/QtCore/qvector.h \
		../miniconda2/include/qt/QtGui/qmatrix.h \
		../miniconda2/include/qt/QtGui/qpolygon.h \
		../miniconda2/include/qt/QtGui/qregion.h \
		../miniconda2/include/qt/QtCore/qdatastream.h \
		../miniconda2/include/qt/QtCore/qiodevice.h \
		../miniconda2/include/qt/QtCore/qline.h \
		../miniconda2/include/qt/QtGui/qtransform.h \
		../miniconda2/include/qt/QtGui/qpainterpath.h \
		../miniconda2/include/qt/QtGui/qimage.h \
		../miniconda2/include/qt/QtGui/qpixelformat.h \
		../miniconda2/include/qt/QtGui/qpixmap.h \
		../miniconda2/include/qt/QtCore/qsharedpointer.h \
		../miniconda2/include/qt/QtCore/qshareddata.h \
		../miniconda2/include/qt/QtCore/qhash.h \
		../miniconda2/include/qt/QtCore/qsharedpointer_impl.h \
		../miniconda2/include/qt/QtGui/qfont.h \
		../miniconda2/include/qt/QtGui/qfontmetrics.h \
		../miniconda2/include/qt/QtGui/qfontinfo.h \
		../miniconda2/include/qt/QtWidgets/qsizepolicy.h \
		../miniconda2/include/qt/QtGui/qcursor.h \
		../miniconda2/include/qt/QtGui/qkeysequence.h \
		../miniconda2/include/qt/QtGui/qevent.h \
		../miniconda2/include/qt/QtCore/qvariant.h \
		../miniconda2/include/qt/QtCore/qmap.h \
		../miniconda2/include/qt/QtCore/qdebug.h \
		../miniconda2/include/qt/QtCore/qtextstream.h \
		../miniconda2/include/qt/QtCore/qlocale.h \
		../miniconda2/include/qt/QtCore/qset.h \
		../miniconda2/include/qt/QtCore/qcontiguouscache.h \
		../miniconda2/include/qt/QtCore/qurl.h \
		../miniconda2/include/qt/QtCore/qurlquery.h \
		../miniconda2/include/qt/QtCore/qfile.h \
		../miniconda2/include/qt/QtCore/qfiledevice.h \
		../miniconda2/include/qt/QtGui/qvector2d.h \
		../miniconda2/include/qt/QtGui/qtouchdevice.h \
		../miniconda2/include/qt/QtWidgets/qtabwidget.h \
		../miniconda2/include/qt/QtGui/qicon.h \
		client.h \
		../miniconda2/include/qt/QtCore/QObject \
		../miniconda2/include/qt/QtCore/QDebug \
		../miniconda2/include/qt/QtWidgets/QFileDialog \
		../miniconda2/include/qt/QtWidgets/qfiledialog.h \
		../miniconda2/include/qt/QtCore/qdir.h \
		../miniconda2/include/qt/QtCore/qfileinfo.h \
		../miniconda2/include/qt/QtWidgets/qdialog.h \
		../miniconda2/include/qt/QtWidgets/QDockWidget \
		../miniconda2/include/qt/QtWidgets/qdockwidget.h \
		../miniconda2/include/qt/QtWidgets/QMessageBox \
		../miniconda2/include/qt/QtWidgets/qmessagebox.h \
		../miniconda2/include/qt/QtWidgets/QGraphicsScene \
		../miniconda2/include/qt/QtWidgets/qgraphicsscene.h \
		../miniconda2/include/qt/QtGui/qpen.h \
		../miniconda2/include/qt/QtCore/QBuffer \
		../miniconda2/include/qt/QtCore/qbuffer.h \
		../miniconda2/include/qt/QtWidgets/QDialog \
		../miniconda2/include/qt/QtCore/QString \
		../miniconda2/include/qt/QtCore/QFile \
		../miniconda2/include/qt/QtNetwork/QTcpSocket \
		../miniconda2/include/qt/QtNetwork/qtcpsocket.h \
		../miniconda2/include/qt/QtNetwork/qtnetworkglobal.h \
		../miniconda2/include/qt/QtNetwork/qtnetwork-config.h \
		../miniconda2/include/qt/QtNetwork/qabstractsocket.h \
		../miniconda2/include/qt/QtNetwork/QUdpSocket \
		../miniconda2/include/qt/QtNetwork/qudpsocket.h \
		../miniconda2/include/qt/QtNetwork/qhostaddress.h \
		../miniconda2/include/qt/QtNetwork/QTcpServer \
		../miniconda2/include/qt/QtNetwork/qtcpserver.h \
		../miniconda2/include/qt/QtNetwork/QNetworkInterface \
		../miniconda2/include/qt/QtNetwork/qnetworkinterface.h \
		../miniconda2/include/qt/QtNetwork/QNetworkConfigurationManager \
		../miniconda2/include/qt/QtNetwork/qnetworkconfigmanager.h \
		../miniconda2/include/qt/QtNetwork/qnetworkconfiguration.h \
		../miniconda2/include/qt/QtNetwork/QNetworkSession \
		../miniconda2/include/qt/QtNetwork/qnetworksession.h \
		../miniconda2/include/qt/QtCore/QSettings \
		../miniconda2/include/qt/QtCore/qsettings.h \
		server.h \
		../miniconda2/include/qt/QtWidgets/QApplication \
		../miniconda2/include/qt/QtWidgets/qapplication.h \
		../miniconda2/include/qt/QtCore/qcoreapplication.h \
		../miniconda2/include/qt/QtCore/qeventloop.h \
		../miniconda2/include/qt/QtWidgets/qdesktopwidget.h \
		../miniconda2/include/qt/QtGui/qguiapplication.h \
		../miniconda2/include/qt/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../miniconda2/include/qt/QtWidgets/QMainWindow \
		../miniconda2/include/qt/QtWidgets/qmainwindow.h \
		../miniconda2/include/qt/QtWidgets/qtwidgetsglobal.h \
		../miniconda2/include/qt/QtGui/qtguiglobal.h \
		../miniconda2/include/qt/QtCore/qglobal.h \
		../miniconda2/include/qt/QtCore/qconfig-bootstrapped.h \
		../miniconda2/include/qt/QtCore/qconfig.h \
		../miniconda2/include/qt/QtCore/qtcore-config.h \
		../miniconda2/include/qt/QtCore/qsystemdetection.h \
		../miniconda2/include/qt/QtCore/qprocessordetection.h \
		../miniconda2/include/qt/QtCore/qcompilerdetection.h \
		../miniconda2/include/qt/QtCore/qtypeinfo.h \
		../miniconda2/include/qt/QtCore/qsysinfo.h \
		../miniconda2/include/qt/QtCore/qlogging.h \
		../miniconda2/include/qt/QtCore/qflags.h \
		../miniconda2/include/qt/QtCore/qatomic.h \
		../miniconda2/include/qt/QtCore/qbasicatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../miniconda2/include/qt/QtCore/qgenericatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_cxx11.h \
		../miniconda2/include/qt/QtCore/qatomic_msvc.h \
		../miniconda2/include/qt/QtCore/qglobalstatic.h \
		../miniconda2/include/qt/QtCore/qmutex.h \
		../miniconda2/include/qt/QtCore/qnumeric.h \
		../miniconda2/include/qt/QtCore/qversiontagging.h \
		../miniconda2/include/qt/QtGui/qtgui-config.h \
		../miniconda2/include/qt/QtWidgets/qtwidgets-config.h \
		../miniconda2/include/qt/QtWidgets/qwidget.h \
		../miniconda2/include/qt/QtGui/qwindowdefs.h \
		../miniconda2/include/qt/QtCore/qobjectdefs.h \
		../miniconda2/include/qt/QtCore/qnamespace.h \
		../miniconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../miniconda2/include/qt/QtGui/qwindowdefs_win.h \
		../miniconda2/include/qt/QtCore/qobject.h \
		../miniconda2/include/qt/QtCore/qstring.h \
		../miniconda2/include/qt/QtCore/qchar.h \
		../miniconda2/include/qt/QtCore/qbytearray.h \
		../miniconda2/include/qt/QtCore/qrefcount.h \
		../miniconda2/include/qt/QtCore/qarraydata.h \
		../miniconda2/include/qt/QtCore/qstringbuilder.h \
		../miniconda2/include/qt/QtCore/qlist.h \
		../miniconda2/include/qt/QtCore/qalgorithms.h \
		../miniconda2/include/qt/QtCore/qiterator.h \
		../miniconda2/include/qt/QtCore/qhashfunctions.h \
		../miniconda2/include/qt/QtCore/qpair.h \
		../miniconda2/include/qt/QtCore/qbytearraylist.h \
		../miniconda2/include/qt/QtCore/qstringlist.h \
		../miniconda2/include/qt/QtCore/qregexp.h \
		../miniconda2/include/qt/QtCore/qstringmatcher.h \
		../miniconda2/include/qt/QtCore/qcoreevent.h \
		../miniconda2/include/qt/QtCore/qscopedpointer.h \
		../miniconda2/include/qt/QtCore/qmetatype.h \
		../miniconda2/include/qt/QtCore/qvarlengtharray.h \
		../miniconda2/include/qt/QtCore/qcontainerfwd.h \
		../miniconda2/include/qt/QtCore/qobject_impl.h \
		../miniconda2/include/qt/QtCore/qmargins.h \
		../miniconda2/include/qt/QtGui/qpaintdevice.h \
		../miniconda2/include/qt/QtCore/qrect.h \
		../miniconda2/include/qt/QtCore/qsize.h \
		../miniconda2/include/qt/QtCore/qpoint.h \
		../miniconda2/include/qt/QtGui/qpalette.h \
		../miniconda2/include/qt/QtGui/qcolor.h \
		../miniconda2/include/qt/QtGui/qrgb.h \
		../miniconda2/include/qt/QtGui/qrgba64.h \
		../miniconda2/include/qt/QtGui/qbrush.h \
		../miniconda2/include/qt/QtCore/qvector.h \
		../miniconda2/include/qt/QtGui/qmatrix.h \
		../miniconda2/include/qt/QtGui/qpolygon.h \
		../miniconda2/include/qt/QtGui/qregion.h \
		../miniconda2/include/qt/QtCore/qdatastream.h \
		../miniconda2/include/qt/QtCore/qiodevice.h \
		../miniconda2/include/qt/QtCore/qline.h \
		../miniconda2/include/qt/QtGui/qtransform.h \
		../miniconda2/include/qt/QtGui/qpainterpath.h \
		../miniconda2/include/qt/QtGui/qimage.h \
		../miniconda2/include/qt/QtGui/qpixelformat.h \
		../miniconda2/include/qt/QtGui/qpixmap.h \
		../miniconda2/include/qt/QtCore/qsharedpointer.h \
		../miniconda2/include/qt/QtCore/qshareddata.h \
		../miniconda2/include/qt/QtCore/qhash.h \
		../miniconda2/include/qt/QtCore/qsharedpointer_impl.h \
		../miniconda2/include/qt/QtGui/qfont.h \
		../miniconda2/include/qt/QtGui/qfontmetrics.h \
		../miniconda2/include/qt/QtGui/qfontinfo.h \
		../miniconda2/include/qt/QtWidgets/qsizepolicy.h \
		../miniconda2/include/qt/QtGui/qcursor.h \
		../miniconda2/include/qt/QtGui/qkeysequence.h \
		../miniconda2/include/qt/QtGui/qevent.h \
		../miniconda2/include/qt/QtCore/qvariant.h \
		../miniconda2/include/qt/QtCore/qmap.h \
		../miniconda2/include/qt/QtCore/qdebug.h \
		../miniconda2/include/qt/QtCore/qtextstream.h \
		../miniconda2/include/qt/QtCore/qlocale.h \
		../miniconda2/include/qt/QtCore/qset.h \
		../miniconda2/include/qt/QtCore/qcontiguouscache.h \
		../miniconda2/include/qt/QtCore/qurl.h \
		../miniconda2/include/qt/QtCore/qurlquery.h \
		../miniconda2/include/qt/QtCore/qfile.h \
		../miniconda2/include/qt/QtCore/qfiledevice.h \
		../miniconda2/include/qt/QtGui/qvector2d.h \
		../miniconda2/include/qt/QtGui/qtouchdevice.h \
		../miniconda2/include/qt/QtWidgets/qtabwidget.h \
		../miniconda2/include/qt/QtGui/qicon.h \
		client.h \
		../miniconda2/include/qt/QtCore/QObject \
		../miniconda2/include/qt/QtCore/QDebug \
		../miniconda2/include/qt/QtWidgets/QFileDialog \
		../miniconda2/include/qt/QtWidgets/qfiledialog.h \
		../miniconda2/include/qt/QtCore/qdir.h \
		../miniconda2/include/qt/QtCore/qfileinfo.h \
		../miniconda2/include/qt/QtWidgets/qdialog.h \
		../miniconda2/include/qt/QtWidgets/QDockWidget \
		../miniconda2/include/qt/QtWidgets/qdockwidget.h \
		../miniconda2/include/qt/QtWidgets/QMessageBox \
		../miniconda2/include/qt/QtWidgets/qmessagebox.h \
		../miniconda2/include/qt/QtWidgets/QGraphicsScene \
		../miniconda2/include/qt/QtWidgets/qgraphicsscene.h \
		../miniconda2/include/qt/QtGui/qpen.h \
		../miniconda2/include/qt/QtCore/QBuffer \
		../miniconda2/include/qt/QtCore/qbuffer.h \
		../miniconda2/include/qt/QtWidgets/QDialog \
		../miniconda2/include/qt/QtCore/QString \
		../miniconda2/include/qt/QtCore/QFile \
		../miniconda2/include/qt/QtNetwork/QTcpSocket \
		../miniconda2/include/qt/QtNetwork/qtcpsocket.h \
		../miniconda2/include/qt/QtNetwork/qtnetworkglobal.h \
		../miniconda2/include/qt/QtNetwork/qtnetwork-config.h \
		../miniconda2/include/qt/QtNetwork/qabstractsocket.h \
		../miniconda2/include/qt/QtNetwork/QUdpSocket \
		../miniconda2/include/qt/QtNetwork/qudpsocket.h \
		../miniconda2/include/qt/QtNetwork/qhostaddress.h \
		../miniconda2/include/qt/QtNetwork/QTcpServer \
		../miniconda2/include/qt/QtNetwork/qtcpserver.h \
		../miniconda2/include/qt/QtNetwork/QNetworkInterface \
		../miniconda2/include/qt/QtNetwork/qnetworkinterface.h \
		../miniconda2/include/qt/QtNetwork/QNetworkConfigurationManager \
		../miniconda2/include/qt/QtNetwork/qnetworkconfigmanager.h \
		../miniconda2/include/qt/QtNetwork/qnetworkconfiguration.h \
		../miniconda2/include/qt/QtNetwork/QNetworkSession \
		../miniconda2/include/qt/QtNetwork/qnetworksession.h \
		../miniconda2/include/qt/QtCore/QSettings \
		../miniconda2/include/qt/QtCore/qsettings.h \
		server.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

server.o: server.cpp server.h \
		../miniconda2/include/qt/QtCore/QDebug \
		../miniconda2/include/qt/QtCore/qdebug.h \
		../miniconda2/include/qt/QtCore/qalgorithms.h \
		../miniconda2/include/qt/QtCore/qglobal.h \
		../miniconda2/include/qt/QtCore/qconfig-bootstrapped.h \
		../miniconda2/include/qt/QtCore/qconfig.h \
		../miniconda2/include/qt/QtCore/qtcore-config.h \
		../miniconda2/include/qt/QtCore/qsystemdetection.h \
		../miniconda2/include/qt/QtCore/qprocessordetection.h \
		../miniconda2/include/qt/QtCore/qcompilerdetection.h \
		../miniconda2/include/qt/QtCore/qtypeinfo.h \
		../miniconda2/include/qt/QtCore/qsysinfo.h \
		../miniconda2/include/qt/QtCore/qlogging.h \
		../miniconda2/include/qt/QtCore/qflags.h \
		../miniconda2/include/qt/QtCore/qatomic.h \
		../miniconda2/include/qt/QtCore/qbasicatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../miniconda2/include/qt/QtCore/qgenericatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_cxx11.h \
		../miniconda2/include/qt/QtCore/qatomic_msvc.h \
		../miniconda2/include/qt/QtCore/qglobalstatic.h \
		../miniconda2/include/qt/QtCore/qmutex.h \
		../miniconda2/include/qt/QtCore/qnumeric.h \
		../miniconda2/include/qt/QtCore/qversiontagging.h \
		../miniconda2/include/qt/QtCore/qhash.h \
		../miniconda2/include/qt/QtCore/qchar.h \
		../miniconda2/include/qt/QtCore/qiterator.h \
		../miniconda2/include/qt/QtCore/qlist.h \
		../miniconda2/include/qt/QtCore/qrefcount.h \
		../miniconda2/include/qt/QtCore/qarraydata.h \
		../miniconda2/include/qt/QtCore/qhashfunctions.h \
		../miniconda2/include/qt/QtCore/qpair.h \
		../miniconda2/include/qt/QtCore/qbytearraylist.h \
		../miniconda2/include/qt/QtCore/qbytearray.h \
		../miniconda2/include/qt/QtCore/qnamespace.h \
		../miniconda2/include/qt/QtCore/qstring.h \
		../miniconda2/include/qt/QtCore/qstringbuilder.h \
		../miniconda2/include/qt/QtCore/qstringlist.h \
		../miniconda2/include/qt/QtCore/qregexp.h \
		../miniconda2/include/qt/QtCore/qstringmatcher.h \
		../miniconda2/include/qt/QtCore/qmap.h \
		../miniconda2/include/qt/QtCore/qtextstream.h \
		../miniconda2/include/qt/QtCore/qiodevice.h \
		../miniconda2/include/qt/QtCore/qobject.h \
		../miniconda2/include/qt/QtCore/qobjectdefs.h \
		../miniconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../miniconda2/include/qt/QtCore/qcoreevent.h \
		../miniconda2/include/qt/QtCore/qscopedpointer.h \
		../miniconda2/include/qt/QtCore/qmetatype.h \
		../miniconda2/include/qt/QtCore/qvarlengtharray.h \
		../miniconda2/include/qt/QtCore/qcontainerfwd.h \
		../miniconda2/include/qt/QtCore/qobject_impl.h \
		../miniconda2/include/qt/QtCore/qlocale.h \
		../miniconda2/include/qt/QtCore/qvariant.h \
		../miniconda2/include/qt/QtCore/qshareddata.h \
		../miniconda2/include/qt/QtCore/qvector.h \
		../miniconda2/include/qt/QtCore/qpoint.h \
		../miniconda2/include/qt/QtCore/qset.h \
		../miniconda2/include/qt/QtCore/qcontiguouscache.h \
		../miniconda2/include/qt/QtCore/qsharedpointer.h \
		../miniconda2/include/qt/QtCore/qsharedpointer_impl.h \
		../miniconda2/include/qt/QtWidgets/QFileDialog \
		../miniconda2/include/qt/QtWidgets/qfiledialog.h \
		../miniconda2/include/qt/QtWidgets/qtwidgetsglobal.h \
		../miniconda2/include/qt/QtGui/qtguiglobal.h \
		../miniconda2/include/qt/QtGui/qtgui-config.h \
		../miniconda2/include/qt/QtWidgets/qtwidgets-config.h \
		../miniconda2/include/qt/QtCore/qdir.h \
		../miniconda2/include/qt/QtCore/qfileinfo.h \
		../miniconda2/include/qt/QtCore/qfile.h \
		../miniconda2/include/qt/QtCore/qfiledevice.h \
		../miniconda2/include/qt/QtCore/qurl.h \
		../miniconda2/include/qt/QtCore/qurlquery.h \
		../miniconda2/include/qt/QtWidgets/qdialog.h \
		../miniconda2/include/qt/QtWidgets/qwidget.h \
		../miniconda2/include/qt/QtGui/qwindowdefs.h \
		../miniconda2/include/qt/QtGui/qwindowdefs_win.h \
		../miniconda2/include/qt/QtCore/qmargins.h \
		../miniconda2/include/qt/QtGui/qpaintdevice.h \
		../miniconda2/include/qt/QtCore/qrect.h \
		../miniconda2/include/qt/QtCore/qsize.h \
		../miniconda2/include/qt/QtGui/qpalette.h \
		../miniconda2/include/qt/QtGui/qcolor.h \
		../miniconda2/include/qt/QtGui/qrgb.h \
		../miniconda2/include/qt/QtGui/qrgba64.h \
		../miniconda2/include/qt/QtGui/qbrush.h \
		../miniconda2/include/qt/QtGui/qmatrix.h \
		../miniconda2/include/qt/QtGui/qpolygon.h \
		../miniconda2/include/qt/QtGui/qregion.h \
		../miniconda2/include/qt/QtCore/qdatastream.h \
		../miniconda2/include/qt/QtCore/qline.h \
		../miniconda2/include/qt/QtGui/qtransform.h \
		../miniconda2/include/qt/QtGui/qpainterpath.h \
		../miniconda2/include/qt/QtGui/qimage.h \
		../miniconda2/include/qt/QtGui/qpixelformat.h \
		../miniconda2/include/qt/QtGui/qpixmap.h \
		../miniconda2/include/qt/QtGui/qfont.h \
		../miniconda2/include/qt/QtGui/qfontmetrics.h \
		../miniconda2/include/qt/QtGui/qfontinfo.h \
		../miniconda2/include/qt/QtWidgets/qsizepolicy.h \
		../miniconda2/include/qt/QtGui/qcursor.h \
		../miniconda2/include/qt/QtGui/qkeysequence.h \
		../miniconda2/include/qt/QtGui/qevent.h \
		../miniconda2/include/qt/QtGui/qvector2d.h \
		../miniconda2/include/qt/QtGui/qtouchdevice.h \
		../miniconda2/include/qt/QtWidgets/QDockWidget \
		../miniconda2/include/qt/QtWidgets/qdockwidget.h \
		../miniconda2/include/qt/QtWidgets/QMessageBox \
		../miniconda2/include/qt/QtWidgets/qmessagebox.h \
		../miniconda2/include/qt/QtWidgets/QGraphicsScene \
		../miniconda2/include/qt/QtWidgets/qgraphicsscene.h \
		../miniconda2/include/qt/QtGui/qpen.h \
		../miniconda2/include/qt/QtCore/QBuffer \
		../miniconda2/include/qt/QtCore/qbuffer.h \
		../miniconda2/include/qt/QtWidgets/QDialog \
		../miniconda2/include/qt/QtCore/QString \
		../miniconda2/include/qt/QtCore/QObject \
		../miniconda2/include/qt/QtCore/QFile \
		../miniconda2/include/qt/QtNetwork/QTcpSocket \
		../miniconda2/include/qt/QtNetwork/qtcpsocket.h \
		../miniconda2/include/qt/QtNetwork/qtnetworkglobal.h \
		../miniconda2/include/qt/QtNetwork/qtnetwork-config.h \
		../miniconda2/include/qt/QtNetwork/qabstractsocket.h \
		../miniconda2/include/qt/QtNetwork/QUdpSocket \
		../miniconda2/include/qt/QtNetwork/qudpsocket.h \
		../miniconda2/include/qt/QtNetwork/qhostaddress.h \
		../miniconda2/include/qt/QtNetwork/QTcpServer \
		../miniconda2/include/qt/QtNetwork/qtcpserver.h \
		../miniconda2/include/qt/QtNetwork/QNetworkInterface \
		../miniconda2/include/qt/QtNetwork/qnetworkinterface.h \
		../miniconda2/include/qt/QtNetwork/QNetworkConfigurationManager \
		../miniconda2/include/qt/QtNetwork/qnetworkconfigmanager.h \
		../miniconda2/include/qt/QtNetwork/qnetworkconfiguration.h \
		../miniconda2/include/qt/QtNetwork/QNetworkSession \
		../miniconda2/include/qt/QtNetwork/qnetworksession.h \
		../miniconda2/include/qt/QtCore/QSettings \
		../miniconda2/include/qt/QtCore/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o server.o server.cpp

client.o: client.cpp client.h \
		../miniconda2/include/qt/QtCore/QObject \
		../miniconda2/include/qt/QtCore/qobject.h \
		../miniconda2/include/qt/QtCore/qobjectdefs.h \
		../miniconda2/include/qt/QtCore/qnamespace.h \
		../miniconda2/include/qt/QtCore/qglobal.h \
		../miniconda2/include/qt/QtCore/qconfig-bootstrapped.h \
		../miniconda2/include/qt/QtCore/qconfig.h \
		../miniconda2/include/qt/QtCore/qtcore-config.h \
		../miniconda2/include/qt/QtCore/qsystemdetection.h \
		../miniconda2/include/qt/QtCore/qprocessordetection.h \
		../miniconda2/include/qt/QtCore/qcompilerdetection.h \
		../miniconda2/include/qt/QtCore/qtypeinfo.h \
		../miniconda2/include/qt/QtCore/qsysinfo.h \
		../miniconda2/include/qt/QtCore/qlogging.h \
		../miniconda2/include/qt/QtCore/qflags.h \
		../miniconda2/include/qt/QtCore/qatomic.h \
		../miniconda2/include/qt/QtCore/qbasicatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../miniconda2/include/qt/QtCore/qgenericatomic.h \
		../miniconda2/include/qt/QtCore/qatomic_cxx11.h \
		../miniconda2/include/qt/QtCore/qatomic_msvc.h \
		../miniconda2/include/qt/QtCore/qglobalstatic.h \
		../miniconda2/include/qt/QtCore/qmutex.h \
		../miniconda2/include/qt/QtCore/qnumeric.h \
		../miniconda2/include/qt/QtCore/qversiontagging.h \
		../miniconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../miniconda2/include/qt/QtCore/qstring.h \
		../miniconda2/include/qt/QtCore/qchar.h \
		../miniconda2/include/qt/QtCore/qbytearray.h \
		../miniconda2/include/qt/QtCore/qrefcount.h \
		../miniconda2/include/qt/QtCore/qarraydata.h \
		../miniconda2/include/qt/QtCore/qstringbuilder.h \
		../miniconda2/include/qt/QtCore/qlist.h \
		../miniconda2/include/qt/QtCore/qalgorithms.h \
		../miniconda2/include/qt/QtCore/qiterator.h \
		../miniconda2/include/qt/QtCore/qhashfunctions.h \
		../miniconda2/include/qt/QtCore/qpair.h \
		../miniconda2/include/qt/QtCore/qbytearraylist.h \
		../miniconda2/include/qt/QtCore/qstringlist.h \
		../miniconda2/include/qt/QtCore/qregexp.h \
		../miniconda2/include/qt/QtCore/qstringmatcher.h \
		../miniconda2/include/qt/QtCore/qcoreevent.h \
		../miniconda2/include/qt/QtCore/qscopedpointer.h \
		../miniconda2/include/qt/QtCore/qmetatype.h \
		../miniconda2/include/qt/QtCore/qvarlengtharray.h \
		../miniconda2/include/qt/QtCore/qcontainerfwd.h \
		../miniconda2/include/qt/QtCore/qobject_impl.h \
		../miniconda2/include/qt/QtCore/QDebug \
		../miniconda2/include/qt/QtCore/qdebug.h \
		../miniconda2/include/qt/QtCore/qhash.h \
		../miniconda2/include/qt/QtCore/qmap.h \
		../miniconda2/include/qt/QtCore/qtextstream.h \
		../miniconda2/include/qt/QtCore/qiodevice.h \
		../miniconda2/include/qt/QtCore/qlocale.h \
		../miniconda2/include/qt/QtCore/qvariant.h \
		../miniconda2/include/qt/QtCore/qshareddata.h \
		../miniconda2/include/qt/QtCore/qvector.h \
		../miniconda2/include/qt/QtCore/qpoint.h \
		../miniconda2/include/qt/QtCore/qset.h \
		../miniconda2/include/qt/QtCore/qcontiguouscache.h \
		../miniconda2/include/qt/QtCore/qsharedpointer.h \
		../miniconda2/include/qt/QtCore/qsharedpointer_impl.h \
		../miniconda2/include/qt/QtWidgets/QFileDialog \
		../miniconda2/include/qt/QtWidgets/qfiledialog.h \
		../miniconda2/include/qt/QtWidgets/qtwidgetsglobal.h \
		../miniconda2/include/qt/QtGui/qtguiglobal.h \
		../miniconda2/include/qt/QtGui/qtgui-config.h \
		../miniconda2/include/qt/QtWidgets/qtwidgets-config.h \
		../miniconda2/include/qt/QtCore/qdir.h \
		../miniconda2/include/qt/QtCore/qfileinfo.h \
		../miniconda2/include/qt/QtCore/qfile.h \
		../miniconda2/include/qt/QtCore/qfiledevice.h \
		../miniconda2/include/qt/QtCore/qurl.h \
		../miniconda2/include/qt/QtCore/qurlquery.h \
		../miniconda2/include/qt/QtWidgets/qdialog.h \
		../miniconda2/include/qt/QtWidgets/qwidget.h \
		../miniconda2/include/qt/QtGui/qwindowdefs.h \
		../miniconda2/include/qt/QtGui/qwindowdefs_win.h \
		../miniconda2/include/qt/QtCore/qmargins.h \
		../miniconda2/include/qt/QtGui/qpaintdevice.h \
		../miniconda2/include/qt/QtCore/qrect.h \
		../miniconda2/include/qt/QtCore/qsize.h \
		../miniconda2/include/qt/QtGui/qpalette.h \
		../miniconda2/include/qt/QtGui/qcolor.h \
		../miniconda2/include/qt/QtGui/qrgb.h \
		../miniconda2/include/qt/QtGui/qrgba64.h \
		../miniconda2/include/qt/QtGui/qbrush.h \
		../miniconda2/include/qt/QtGui/qmatrix.h \
		../miniconda2/include/qt/QtGui/qpolygon.h \
		../miniconda2/include/qt/QtGui/qregion.h \
		../miniconda2/include/qt/QtCore/qdatastream.h \
		../miniconda2/include/qt/QtCore/qline.h \
		../miniconda2/include/qt/QtGui/qtransform.h \
		../miniconda2/include/qt/QtGui/qpainterpath.h \
		../miniconda2/include/qt/QtGui/qimage.h \
		../miniconda2/include/qt/QtGui/qpixelformat.h \
		../miniconda2/include/qt/QtGui/qpixmap.h \
		../miniconda2/include/qt/QtGui/qfont.h \
		../miniconda2/include/qt/QtGui/qfontmetrics.h \
		../miniconda2/include/qt/QtGui/qfontinfo.h \
		../miniconda2/include/qt/QtWidgets/qsizepolicy.h \
		../miniconda2/include/qt/QtGui/qcursor.h \
		../miniconda2/include/qt/QtGui/qkeysequence.h \
		../miniconda2/include/qt/QtGui/qevent.h \
		../miniconda2/include/qt/QtGui/qvector2d.h \
		../miniconda2/include/qt/QtGui/qtouchdevice.h \
		../miniconda2/include/qt/QtWidgets/QDockWidget \
		../miniconda2/include/qt/QtWidgets/qdockwidget.h \
		../miniconda2/include/qt/QtWidgets/QMessageBox \
		../miniconda2/include/qt/QtWidgets/qmessagebox.h \
		../miniconda2/include/qt/QtWidgets/QGraphicsScene \
		../miniconda2/include/qt/QtWidgets/qgraphicsscene.h \
		../miniconda2/include/qt/QtGui/qpen.h \
		../miniconda2/include/qt/QtCore/QBuffer \
		../miniconda2/include/qt/QtCore/qbuffer.h \
		../miniconda2/include/qt/QtWidgets/QDialog \
		../miniconda2/include/qt/QtCore/QString \
		../miniconda2/include/qt/QtCore/QFile \
		../miniconda2/include/qt/QtNetwork/QTcpSocket \
		../miniconda2/include/qt/QtNetwork/qtcpsocket.h \
		../miniconda2/include/qt/QtNetwork/qtnetworkglobal.h \
		../miniconda2/include/qt/QtNetwork/qtnetwork-config.h \
		../miniconda2/include/qt/QtNetwork/qabstractsocket.h \
		../miniconda2/include/qt/QtNetwork/QUdpSocket \
		../miniconda2/include/qt/QtNetwork/qudpsocket.h \
		../miniconda2/include/qt/QtNetwork/qhostaddress.h \
		../miniconda2/include/qt/QtNetwork/QTcpServer \
		../miniconda2/include/qt/QtNetwork/qtcpserver.h \
		../miniconda2/include/qt/QtNetwork/QNetworkInterface \
		../miniconda2/include/qt/QtNetwork/qnetworkinterface.h \
		../miniconda2/include/qt/QtNetwork/QNetworkConfigurationManager \
		../miniconda2/include/qt/QtNetwork/qnetworkconfigmanager.h \
		../miniconda2/include/qt/QtNetwork/qnetworkconfiguration.h \
		../miniconda2/include/qt/QtNetwork/QNetworkSession \
		../miniconda2/include/qt/QtNetwork/qnetworksession.h \
		../miniconda2/include/qt/QtCore/QSettings \
		../miniconda2/include/qt/QtCore/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o client.o client.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_server.o: moc_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_server.o moc_server.cpp

moc_client.o: moc_client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_client.o moc_client.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

